### ISSUE TITLE
Error importing FBX character

### ISSUE THREAD

**Issue by riccardo-runci** [valentinwinkelmann/CC2UMAConverter#1]
Hi, first of all thank you for this fantastic plugin.

I'm trying to import a character from CC4 (exported with the correct settings) via the blender addon, but once imported the pose is not set correctly, I share a screenshot here. When I click on convert I also get errors in the console

https://imgur.com/a/kEJ8LPy

console error:
https://imgur.com/3OsYXUW

export settings from cc4:
https://imgur.com/a/RBlKEj9

EDIT:
I solved the mesh rotation problem, just unbind the armature, rotate the mesh and rebind it. And commented the line 148/149 of the script and it work, i have imported the model in unity and the race creation are done. But the character seems to have no dna and no expression support, i have to create it manually from uma?

**Comment by valentinwinkelmann** [comment]
Sorry for the very delayed response, I had to take care of other projects. With https://github.com/valentinwinkelmann/CC2UMAConverter/commit/9d7c04915772c0578ab269dff8054e9832512ba4 this should be fixed. Currently, there is only to be a basic race created which can be clothed, but there is no DNA or Expression created.
However, since the plugin retains the blendshapes in the mesh, it is possible to create them manually in Unity. I don't use it myself at the moment, so I haven't researched how to deal with blendshapes, DNA and expressions.
